version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      #- run:
      #    name: lint
      #    command: yarn run lint:ci

      #- run:
      #    name:  test
      #    command: yarn run test:ci

      - run:
          name: build
          command: yarn run build

      - persist_to_workspace:
          root: .
          paths:
            - src/storybook/dist/*
            - src/modul-website/dist/*

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  buildimage:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: "Setup tag name environment variables"
          command: |
            echo 'export TAG_NAME=${CIRCLE_BRANCH//[_/]/-} >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV

      - attach_workspace:
          at: ~/repo

      - run:
          name: "list dir"
          command: ls

      - run:
          name: "list dirworksapce"
          command: ls  ~/repo/src/storybook/dist

      - run:
          name: "What branch am I on?"
          command: echo ${TAG_NAME}
workflows:
  version: 2
  one_and_two:
     jobs:
       - build
       - buildimage:
          requires:
            - build

