version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      #- run:
      #    name: lint
      #    command: yarn run lint:ci

      #- run:
      #    name:  test
      #    command: yarn run test:ci

      - run:
          name: build
          command: yarn run build:ci

      - persist_to_workspace:
          root: .
          paths:
            - src/storybook/dist/*
            - src/modul-website/dist/*

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  publish_image:
    docker:
      - image: circleci/buildpack-deps:stretch

    working_directory: ~/repo

    steps:

      - checkout

      - setup_remote_docker

      - attach_workspace:
          at: ~/repo

      - run:
          name: "Setup tag name as environment variables"
          command: |
             echo "export TAG_NAME=$(echo ${CIRCLE_BRANCH} | sed -r 's/[_/]+/-/g' | cut -c1-127)" >> $BASH_ENV # Redirect TAG_NAME into $BASH_ENV

      - run:
          name: "What TAG_NAME is set?"
          command: echo $TAG_NAME

      - run:
          name: Build Docker image
          command: |
              docker build -t ulaval/modul:${TAG_NAME} .

      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push ulaval/modul:${TAG_NAME}
workflows:
  version: 2
  build_and_publish_image:
     jobs:
       - build
       - publish_image:
          requires:
            - build

