version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      #- run:
      #    name: lint
      #    command: yarn run lint:ci

      #- run:
      #    name:  test
      #    command: yarn run test:ci

      - run:
          name: build
          command: yarn run build:ci

      - persist_to_workspace:
          root: .
          paths:
            - src/storybook/dist/*
            - src/modul-website/dist/*

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  buildimage:
    docker:
      - image: circleci/buildpack-deps:stretch

    working_directory: ~/repo

    steps:

      - checkout

      - setup_remote_docker

      - run:
          name: "Setup tag name environment variables"
          command: |
            echo "${CIRCLE_BRANCH}" | sed -r 's/[_/]+/-/g' >> $BASH_ENV # Redirect TAG_NAME into $BASH_ENV
      - attach_workspace:
          at: ~/repo

      - run:
          name: "list dir"
          command: ls

      - run:
          name: "list dirworksapce"
          command: ls  ~/repo/src/storybook/dist/assets

      - run:
          name: "What branch am I on?"
          command: echo ${TAG_NAME}

      - run:
          name: Build Docker image
          command: |
              docker build -t chocmah/modul:${TAG_NAME} .

      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:${TAG_NAME}
workflows:
  version: 2
  one_and_two:
     jobs:
       - build
       - buildimage:
          requires:
            - build

