version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - run:
          name: lint
          command: yarn run lint:ci

      - run:
          name:  test
          command: yarn run test:ci

      - run:
          name: build
          command: yarn run build

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  buildimage:
    machine: true

    steps:
      - run:
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}


