
import MSvgAddCircleFilled from '@ulaval/modul-components/dist/assets/icons/svg/add-circle-filled.svg';
import MSvgAddCircle from '@ulaval/modul-components/dist/assets/icons/svg/add-circle.svg';
import MSvgArrowDown from '@ulaval/modul-components/dist/assets/icons/svg/arrow--down.svg';
import MSvgArrowLeft from '@ulaval/modul-components/dist/assets/icons/svg/arrow--left.svg';
import MSvgArrowRight from '@ulaval/modul-components/dist/assets/icons/svg/arrow--right.svg';
import MSvgArrowUp from '@ulaval/modul-components/dist/assets/icons/svg/arrow--up.svg';
import MSvgArrowButtonDown from '@ulaval/modul-components/dist/assets/icons/svg/arrow-button--down.svg';
import MSvgArrowButtonLeft from '@ulaval/modul-components/dist/assets/icons/svg/arrow-button--left.svg';
import MSvgArrowButtonRight from '@ulaval/modul-components/dist/assets/icons/svg/arrow-button--right.svg';
import MSvgArrowButtonUp from '@ulaval/modul-components/dist/assets/icons/svg/arrow-button--up.svg';
import MSvgArrowHeadCircleRight from '@ulaval/modul-components/dist/assets/icons/svg/arrow-head-circle--right.svg';
import MSvgArrowHeadFilledDown from '@ulaval/modul-components/dist/assets/icons/svg/arrow-head-filled--down.svg';
import MSvgArrowHeadFilledLeft from '@ulaval/modul-components/dist/assets/icons/svg/arrow-head-filled--left.svg';
import MSvgArrowHeadFilledRight from '@ulaval/modul-components/dist/assets/icons/svg/arrow-head-filled--right.svg';
import MSvgArrowHeadFilledUp from '@ulaval/modul-components/dist/assets/icons/svg/arrow-head-filled--up.svg';
import MSvgArrowReturn from '@ulaval/modul-components/dist/assets/icons/svg/arrow-return.svg';
import MSvgArrowThinDown from '@ulaval/modul-components/dist/assets/icons/svg/arrow-thin--down.svg';
import MSvgArrowThinLeft from '@ulaval/modul-components/dist/assets/icons/svg/arrow-thin--left.svg';
import MSvgArrowThinRight from '@ulaval/modul-components/dist/assets/icons/svg/arrow-thin--right.svg';
import MSvgArrowThinUp from '@ulaval/modul-components/dist/assets/icons/svg/arrow-thin--up.svg';
import MSvgAttachment from '@ulaval/modul-components/dist/assets/icons/svg/attachment.svg';
import MSvgAvatar from '@ulaval/modul-components/dist/assets/icons/svg/avatar.svg';
import MSvgLock from '@ulaval/modul-components/dist/assets/icons/svg/lock.svg';
import MSvgMessageErrorAccessDenied from '@ulaval/modul-components/dist/assets/icons/svg/message-error-access-denied.svg';
import MSvgMessageErrorBrowserNotSupported from '@ulaval/modul-components/dist/assets/icons/svg/message-error-browser-not-supported.svg';
import MSvgMessageErrorConfigNotSupported from '@ulaval/modul-components/dist/assets/icons/svg/message-error-config-not-supported.svg';
import MSvgMessageErrorConflict from '@ulaval/modul-components/dist/assets/icons/svg/message-error-conflict.svg';
import MSvgMessageErrorCookiesDisabled from '@ulaval/modul-components/dist/assets/icons/svg/message-error-cookies-disabled.svg';
import MSvgMessageErrorPageNotFound from '@ulaval/modul-components/dist/assets/icons/svg/message-error-page-not-found.svg';
import MSvgMessageErrorResourceUnavailable from '@ulaval/modul-components/dist/assets/icons/svg/message-error-resource-unavailable.svg';
import MSvgMessageErrorTechnicalDifficulty from '@ulaval/modul-components/dist/assets/icons/svg/message-error-technical-difficulty.svg';
import MSvgProfile from '@ulaval/modul-components/dist/assets/icons/svg/profile.svg';
import { ModulIconName } from '@ulaval/modul-components/dist/utils/modul-icons/modul-icons';
import { SvgSpriteService } from '@ulaval/modul-components/dist/utils/svg/svg-sprite';
import Vue from 'vue';

export const importAllSvg: () => void = () => {
    const svg: SvgSpriteService = Vue.prototype.$svgSprite;
    svg.addSvg(ModulIconName.AddCircleFilled, MSvgAddCircleFilled);
    svg.addSvg(ModulIconName.AddCircle, MSvgAddCircle);
    svg.addSvg(ModulIconName.ArrowDown, MSvgArrowDown);
    svg.addSvg(ModulIconName.ArrowLeft, MSvgArrowLeft);
    svg.addSvg(ModulIconName.ArrowRight, MSvgArrowRight);
    svg.addSvg(ModulIconName.ArrowUp, MSvgArrowUp);
    svg.addSvg(ModulIconName.ArrowButtonDown, MSvgArrowButtonDown);
    svg.addSvg(ModulIconName.ArrowButtonRight, MSvgArrowButtonRight);
    svg.addSvg(ModulIconName.ArrowButtonLeft, MSvgArrowButtonLeft);
    svg.addSvg(ModulIconName.ArrowButtonUp, MSvgArrowButtonUp);

    svg.addSvg(ModulIconName.ArrowHeadCircleRight, MSvgArrowHeadCircleRight);
    svg.addSvg(ModulIconName.ArrowHeadFilledDown, MSvgArrowHeadFilledDown);
    svg.addSvg(ModulIconName.ArrowHeadFilledLeft, MSvgArrowHeadFilledLeft);
    svg.addSvg(ModulIconName.ArrowHeadFilledRight, MSvgArrowHeadFilledRight);
    svg.addSvg(ModulIconName.ArrowHeadFilledUp, MSvgArrowHeadFilledUp);
    svg.addSvg(ModulIconName.ArrowReturn, MSvgArrowReturn);
    svg.addSvg(ModulIconName.ArrowThinDown, MSvgArrowThinDown);
    svg.addSvg(ModulIconName.ArrowThinLeft, MSvgArrowThinLeft);
    svg.addSvg(ModulIconName.ArrowThinRight, MSvgArrowThinRight);
    svg.addSvg(ModulIconName.ArrowThinUp, MSvgArrowThinUp);
    svg.addSvg(ModulIconName.Attachment, MSvgAttachment);
    svg.addSvg(ModulIconName.Avatar, MSvgAvatar);
    // svg.addSvg(ModulIconName.Calendar, MSvgCalendar);
    // svg.addSvg(ModulIconName.ChevronDown, MSvgChevronDown);
    // svg.addSvg(ModulIconName.ChevronLeft, MSvgChevronLeft);
    // svg.addSvg(ModulIconName.ChevronRight, MSvgChevronRight);
    // svg.addSvg(ModulIconName.ChevronUp, MSvgChevronUp);
    // svg.addSvg(ModulIconName.Clock, MSvgClock);
    // svg.addSvg(ModulIconName.CloseClear, MSvgCloseClear);
    // svg.addSvg(ModulIconName.CodeTag, MSvgCodeTag);
    // svg.addSvg(ModulIconName.CompletedFilled, MSvgCompletedFilled);
    // svg.addSvg(ModulIconName.ConfirmationWhiteFilled, MSvgConfirmationWhiteFilled);
    // svg.addSvg(ModulIconName.Confirmation, MSvgConfirmation);
    // svg.addSvg(ModulIconName.Download MSvgDownload);
    // svg.addSvg(ModulIconName.DragVertical, MSvgDragVertical);
    // svg.addSvg(ModulIconName.Dragndrop, MSvgDragndrop);

    svg.addSvg(ModulIconName.Lock, MSvgLock);
    svg.addSvg(ModulIconName.MessageErrorAccessDenied, MSvgMessageErrorAccessDenied);
    svg.addSvg(ModulIconName.MessageErrorBrowserNotSupported, MSvgMessageErrorBrowserNotSupported);
    svg.addSvg(ModulIconName.MessageErrorConfigNotSupported, MSvgMessageErrorConfigNotSupported);
    svg.addSvg(ModulIconName.MessageErrorConflict, MSvgMessageErrorConflict);
    svg.addSvg(ModulIconName.MessageErrorCookiesDisabled, MSvgMessageErrorCookiesDisabled);
    svg.addSvg(ModulIconName.MessageErrorPageNotFound, MSvgMessageErrorPageNotFound);
    svg.addSvg(ModulIconName.MessageErrorResourceUnavailable, MSvgMessageErrorResourceUnavailable);
    svg.addSvg(ModulIconName.MessageErrorTechnicalDifficulty, MSvgMessageErrorTechnicalDifficulty);
    svg.addSvg(ModulIconName.Profile, MSvgProfile);
};
