import AccordionGroupPlugin from '@ulaval/modul-components/dist/components/accordion-group/accordion-group';
import AccordionPlugin from '@ulaval/modul-components/dist/components/accordion/accordion';
import AddPlugin from '@ulaval/modul-components/dist/components/add/add';
import ButtonPlugin from '@ulaval/modul-components/dist/components/button/button';
import CarouselPlugin from '@ulaval/modul-components/dist/components/carousel/carousel';
import CheckboxPlugin from '@ulaval/modul-components/dist/components/checkbox/checkbox';
import DaterangepickerPlugin from '@ulaval/modul-components/dist/components/daterangepicker/daterangepicker';
import DialogPlugin from '@ulaval/modul-components/dist/components/dialog/dialog';
import DropdownPlugin from '@ulaval/modul-components/dist/components/dropdown/dropdown';
import ExpandableLayoutPlugin from '@ulaval/modul-components/dist/components/expandable-layout/expandable-layout';
import FileSelectPlugin from '@ulaval/modul-components/dist/components/file-select/file-select';
import FileUploadPlugin from '@ulaval/modul-components/dist/components/file-upload/file-upload';
import I18nPlugin from '@ulaval/modul-components/dist/components/i18n/i18n';
import IconButtonPlugin from '@ulaval/modul-components/dist/components/icon-button/icon-button';
import IconFilePlugin from '@ulaval/modul-components/dist/components/icon-file/icon-file';
import IconPlugin from '@ulaval/modul-components/dist/components/icon/icon';
import InplaceEditPlugin from '@ulaval/modul-components/dist/components/inplace-edit/inplace-edit';
import LimitTextPlugin from '@ulaval/modul-components/dist/components/limit-text/limit-text';
import LinkPlugin from '@ulaval/modul-components/dist/components/link/link';
import ListItemPlugin from '@ulaval/modul-components/dist/components/list-item/list-item';
import MenuPlugin from '@ulaval/modul-components/dist/components/menu/menu';
import MessagePlugin from '@ulaval/modul-components/dist/components/message/message';
import ModalPlugin from '@ulaval/modul-components/dist/components/modal/modal';
import NavbarPlugin from '@ulaval/modul-components/dist/components/navbar/navbar';
import OptionPlugin from '@ulaval/modul-components/dist/components/option/option';
import OverlayPlugin from '@ulaval/modul-components/dist/components/overlay/overlay';
import PanelPlugin from '@ulaval/modul-components/dist/components/panel/panel';
import PopupPlugin from '@ulaval/modul-components/dist/components/popup/popup';
import ProgressPlugin from '@ulaval/modul-components/dist/components/progress/progress';
import RadioGroupPlugin from '@ulaval/modul-components/dist/components/radio-group/radio-group';
import SearchfieldPlugin from '@ulaval/modul-components/dist/components/searchfield/searchfield';
import ShowMorePlugin from '@ulaval/modul-components/dist/components/show-more/show-more';
import SliderPlugin from '@ulaval/modul-components/dist/components/slider/slider';
import TextareaPlugin from '@ulaval/modul-components/dist/components/textarea/textarea';
import TextfieldPlugin from '@ulaval/modul-components/dist/components/textfield/textfield';
import { UtilsPlugin } from '@ulaval/modul-components/dist/utils';
import ScrollToPlugin from '@ulaval/modul-components/dist/utils/scroll-to/scroll-to';
import Vue, { PluginObject } from 'vue';

const ModulPlugin: PluginObject<any> = {
    install(v, options): void {

        Vue.use(UtilsPlugin, { propagateVueParserErrors: false, i18PluginOptions: { curLang: options.curLang } });
        Vue.use(I18nPlugin);
        Vue.use(IconPlugin);
        Vue.use(IconButtonPlugin);
        Vue.use(AccordionPlugin);
        Vue.use(NavbarPlugin);
        Vue.use(LinkPlugin);
        Vue.use(ModalPlugin);
        Vue.use(SliderPlugin);
        Vue.use(DropdownPlugin);
        Vue.use(TextfieldPlugin);
        Vue.use(PanelPlugin);
        Vue.use(MessagePlugin);
        Vue.use(SearchfieldPlugin);
        Vue.use(ButtonPlugin);
        Vue.use(ExpandableLayoutPlugin);
        Vue.use(CarouselPlugin);
        Vue.use(CheckboxPlugin);
        Vue.use(AccordionGroupPlugin);
        Vue.use(DaterangepickerPlugin);
        Vue.use(DialogPlugin);
        Vue.use(FileUploadPlugin);
        Vue.use(FileSelectPlugin);
        Vue.use(IconFilePlugin);
        Vue.use(InplaceEditPlugin);
        Vue.use(TextareaPlugin);
        Vue.use(LimitTextPlugin);
        Vue.use(ListItemPlugin);
        Vue.use(MenuPlugin);
        Vue.use(MessagePlugin);
        Vue.use(ModalPlugin);
        Vue.use(NavbarPlugin);
        Vue.use(OptionPlugin);
        Vue.use(OverlayPlugin);
        Vue.use(AddPlugin);
        Vue.use(PopupPlugin);
        Vue.use(ProgressPlugin);
        Vue.use(RadioGroupPlugin);
        Vue.use(ScrollToPlugin);
        Vue.use(ShowMorePlugin);
    }
};

export default ModulPlugin;
